title:            Rails Girls Chișinău
email:            railsgirlsmd@gmail.com
description: >
                  Rails Girls Chișinău is series of free workshops aimed at teaching
                  girls and women the basics of web development with Ruby on Rails framework.
baseurl:          ""
url:              http://railsgirlschisinau.github.io
github:
  url:            #"https://github.com/railsgirlschisinau"
twitter_username: RailsGirlsMD
github_username:  rails-girls-chisinau-website
facebook:
  app_id:         170933873606078

markdown:         kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
image:
  path: sec2.jpg
